# Generated by Django 4.1.3 on 2022-11-17 16:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Содержание')),
                ('created_at', models.TimeField(auto_now_add=True, verbose_name='Создано')),
                ('modified_at', models.TimeField(auto_now=True, verbose_name='Изменено')),
                ('dislikes', models.ManyToManyField(related_name='question_dislikes', to=settings.AUTH_USER_MODEL, verbose_name='Дизлайки')),
                ('likes', models.ManyToManyField(related_name='question_likes', to=settings.AUTH_USER_MODEL, verbose_name='Лайки')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('created_at', models.TimeField(auto_now_add=True, verbose_name='Создано')),
                ('modified_at', models.TimeField(auto_now=True, verbose_name='Изменено')),
                ('dislikes', models.ManyToManyField(related_name='comment_dislikes', to=settings.AUTH_USER_MODEL, verbose_name='Дизлайки')),
                ('likes', models.ManyToManyField(related_name='comment_likes', to=settings.AUTH_USER_MODEL, verbose_name='Лайки')),
            ],
        ),
    ]
