# Generated by Django 4.1.3 on 2022-11-18 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_comment_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
