# Generated by Django 4.1.3 on 2022-11-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_alter_question_created_at_alter_question_modified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='%Y/%m/%d', verbose_name='Фотография профиля'),
        ),
    ]
