# Generated by Django 4.1.3 on 2022-11-22 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0010_alter_comment_created_at_alter_comment_modified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_solution',
            field=models.BooleanField(default=False, verbose_name='Решение вопроса'),
        ),
    ]
