# Generated by Django 4.1.3 on 2022-11-23 08:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0014_alter_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='comments_disliked_by_user', to=settings.AUTH_USER_MODEL, verbose_name='Дизлайки'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='comments_liked_by_user', to=settings.AUTH_USER_MODEL, verbose_name='Лайки'),
        ),
        migrations.AlterField(
            model_name='question',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='question_disliked_by_user', to=settings.AUTH_USER_MODEL, verbose_name='Дизлайки'),
        ),
        migrations.AlterField(
            model_name='question',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='questions_liked_by_user', to=settings.AUTH_USER_MODEL, verbose_name='Лайки'),
        ),
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='questions_by_tag', to='questions.tag', verbose_name='Теги'),
        ),
    ]
